### ISSUE TITLE
Image not publicly accessable?

### ISSUE THREAD

**Issue by rhochmayr** [Lilypad-Tech/lilypad-module-lilysay#2]
Hi there

Is it possible that the image is not publicly accessible or needing authentication? I can't seem to get it to work with this.

https://github.com/Lilypad-Tech/lilypad-module-lilysay/blob/8ad04a27923edb8d7f68222cac24accc803219cc/lilypad_module.json.tmpl#L23

I tried it with the following and that does get processed on my rp/node:
```
        "Image": "lilypadnetwork/lilysay:0.0.6"
```

**Comment by developersteve** [comment]
Hi @rhochmayr, good catch. Ive just fixed tagged version `0.5.2`

see if this works... 

```lilypad run github.com/lilypad-tech/lilypad-module-lilysay:0.5.2 -i Message='Hello lilypad world'```

The image in the template needs to point to where the containerised image is stored to be run on the network, in this case it was using an older base image link from the ECR we use.
